// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: router/rules.proto

package router

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RoutingRules int32

const (
	RoutingRules_RoutingRules_UNDEFINED      RoutingRules = 0
	RoutingRules_RoutingRule_TRAFFIC_BASED   RoutingRules = 1
	RoutingRules_RoutingRules_PAY_MODE_BASED RoutingRules = 2
)

// Enum value maps for RoutingRules.
var (
	RoutingRules_name = map[int32]string{
		0: "RoutingRules_UNDEFINED",
		1: "RoutingRule_TRAFFIC_BASED",
		2: "RoutingRules_PAY_MODE_BASED",
	}
	RoutingRules_value = map[string]int32{
		"RoutingRules_UNDEFINED":      0,
		"RoutingRule_TRAFFIC_BASED":   1,
		"RoutingRules_PAY_MODE_BASED": 2,
	}
)

func (x RoutingRules) Enum() *RoutingRules {
	p := new(RoutingRules)
	*p = x
	return p
}

func (x RoutingRules) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoutingRules) Descriptor() protoreflect.EnumDescriptor {
	return file_router_rules_proto_enumTypes[0].Descriptor()
}

func (RoutingRules) Type() protoreflect.EnumType {
	return &file_router_rules_proto_enumTypes[0]
}

func (x RoutingRules) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoutingRules.Descriptor instead.
func (RoutingRules) EnumDescriptor() ([]byte, []int) {
	return file_router_rules_proto_rawDescGZIP(), []int{0}
}

type TrafficBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Split map[string]float32 `protobuf:"bytes,1,rep,name=split,proto3" json:"split,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed32,2,opt,name=value,proto3"` // Bank -> % traffic
}

func (x *TrafficBased) Reset() {
	*x = TrafficBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_rules_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrafficBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficBased) ProtoMessage() {}

func (x *TrafficBased) ProtoReflect() protoreflect.Message {
	mi := &file_router_rules_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficBased.ProtoReflect.Descriptor instead.
func (*TrafficBased) Descriptor() ([]byte, []int) {
	return file_router_rules_proto_rawDescGZIP(), []int{0}
}

func (x *TrafficBased) GetSplit() map[string]float32 {
	if x != nil {
		return x.Split
	}
	return nil
}

type PayModeBased struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Split map[string]string `protobuf:"bytes,1,rep,name=split,proto3" json:"split,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"` // PayMode -> Bank
}

func (x *PayModeBased) Reset() {
	*x = PayModeBased{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_rules_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayModeBased) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayModeBased) ProtoMessage() {}

func (x *PayModeBased) ProtoReflect() protoreflect.Message {
	mi := &file_router_rules_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayModeBased.ProtoReflect.Descriptor instead.
func (*PayModeBased) Descriptor() ([]byte, []int) {
	return file_router_rules_proto_rawDescGZIP(), []int{1}
}

func (x *PayModeBased) GetSplit() map[string]string {
	if x != nil {
		return x.Split
	}
	return nil
}

var File_router_rules_proto protoreflect.FileDescriptor

var file_router_rules_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6c, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x22, 0x7f, 0x0a, 0x0c,
	0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x05,
	0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x42, 0x61, 0x73, 0x65,
	0x64, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73, 0x70,
	0x6c, 0x69, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x7f, 0x0a,
	0x0c, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x35, 0x0a,
	0x05, 0x73, 0x70, 0x6c, 0x69, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x73,
	0x65, 0x64, 0x2e, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x73,
	0x70, 0x6c, 0x69, 0x74, 0x1a, 0x38, 0x0a, 0x0a, 0x53, 0x70, 0x6c, 0x69, 0x74, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x2a, 0x6a,
	0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x12, 0x1a,
	0x0a, 0x16, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x55,
	0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x19, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x5f, 0x54, 0x52, 0x41, 0x46, 0x46, 0x49,
	0x43, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x44, 0x10, 0x01, 0x12, 0x1f, 0x0a, 0x1b, 0x52, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x5f, 0x50, 0x41, 0x59, 0x5f, 0x4d, 0x4f,
	0x44, 0x45, 0x5f, 0x42, 0x41, 0x53, 0x45, 0x44, 0x10, 0x02, 0x42, 0x1b, 0x5a, 0x19, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_router_rules_proto_rawDescOnce sync.Once
	file_router_rules_proto_rawDescData = file_router_rules_proto_rawDesc
)

func file_router_rules_proto_rawDescGZIP() []byte {
	file_router_rules_proto_rawDescOnce.Do(func() {
		file_router_rules_proto_rawDescData = protoimpl.X.CompressGZIP(file_router_rules_proto_rawDescData)
	})
	return file_router_rules_proto_rawDescData
}

var file_router_rules_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_router_rules_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_router_rules_proto_goTypes = []interface{}{
	(RoutingRules)(0),    // 0: router.RoutingRules
	(*TrafficBased)(nil), // 1: router.TrafficBased
	(*PayModeBased)(nil), // 2: router.PayModeBased
	nil,                  // 3: router.TrafficBased.SplitEntry
	nil,                  // 4: router.PayModeBased.SplitEntry
}
var file_router_rules_proto_depIdxs = []int32{
	3, // 0: router.TrafficBased.split:type_name -> router.TrafficBased.SplitEntry
	4, // 1: router.PayModeBased.split:type_name -> router.PayModeBased.SplitEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_router_rules_proto_init() }
func file_router_rules_proto_init() {
	if File_router_rules_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_router_rules_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrafficBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_router_rules_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayModeBased); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_router_rules_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_router_rules_proto_goTypes,
		DependencyIndexes: file_router_rules_proto_depIdxs,
		EnumInfos:         file_router_rules_proto_enumTypes,
		MessageInfos:      file_router_rules_proto_msgTypes,
	}.Build()
	File_router_rules_proto = out.File
	file_router_rules_proto_rawDesc = nil
	file_router_rules_proto_goTypes = nil
	file_router_rules_proto_depIdxs = nil
}
