// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: router/service.proto

package router

import (
	status "google.golang.org/genproto/googleapis/rpc/status"
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	pay "paymentGateway/api/pay"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RouteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Money      *money.Money `protobuf:"bytes,1,opt,name=money,proto3" json:"money,omitempty"`
	Paymode    *pay.PayMode `protobuf:"bytes,2,opt,name=paymode,proto3" json:"paymode,omitempty"`
	ClientCode string       `protobuf:"bytes,3,opt,name=client_code,json=clientCode,proto3" json:"client_code,omitempty"`
}

func (x *RouteRequest) Reset() {
	*x = RouteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteRequest) ProtoMessage() {}

func (x *RouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteRequest.ProtoReflect.Descriptor instead.
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return file_router_service_proto_rawDescGZIP(), []int{0}
}

func (x *RouteRequest) GetMoney() *money.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *RouteRequest) GetPaymode() *pay.PayMode {
	if x != nil {
		return x.Paymode
	}
	return nil
}

func (x *RouteRequest) GetClientCode() string {
	if x != nil {
		return x.ClientCode
	}
	return ""
}

type RouteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *RouteResponse) Reset() {
	*x = RouteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteResponse) ProtoMessage() {}

func (x *RouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteResponse.ProtoReflect.Descriptor instead.
func (*RouteResponse) Descriptor() ([]byte, []int) {
	return file_router_service_proto_rawDescGZIP(), []int{1}
}

func (x *RouteResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

type SetRoutingRuleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client   string       `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	RuleType RoutingRules `protobuf:"varint,2,opt,name=rule_type,json=ruleType,proto3,enum=router.RoutingRules" json:"rule_type,omitempty"`
	// Types that are assignable to Rule:
	//
	//	*SetRoutingRuleRequest_TrafficBased
	//	*SetRoutingRuleRequest_PaymodeBased
	Rule isSetRoutingRuleRequest_Rule `protobuf_oneof:"rule"`
}

func (x *SetRoutingRuleRequest) Reset() {
	*x = SetRoutingRuleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRoutingRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoutingRuleRequest) ProtoMessage() {}

func (x *SetRoutingRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_router_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoutingRuleRequest.ProtoReflect.Descriptor instead.
func (*SetRoutingRuleRequest) Descriptor() ([]byte, []int) {
	return file_router_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetRoutingRuleRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *SetRoutingRuleRequest) GetRuleType() RoutingRules {
	if x != nil {
		return x.RuleType
	}
	return RoutingRules_RoutingRules_UNDEFINED
}

func (m *SetRoutingRuleRequest) GetRule() isSetRoutingRuleRequest_Rule {
	if m != nil {
		return m.Rule
	}
	return nil
}

func (x *SetRoutingRuleRequest) GetTrafficBased() *TrafficBased {
	if x, ok := x.GetRule().(*SetRoutingRuleRequest_TrafficBased); ok {
		return x.TrafficBased
	}
	return nil
}

func (x *SetRoutingRuleRequest) GetPaymodeBased() *PayModeBased {
	if x, ok := x.GetRule().(*SetRoutingRuleRequest_PaymodeBased); ok {
		return x.PaymodeBased
	}
	return nil
}

type isSetRoutingRuleRequest_Rule interface {
	isSetRoutingRuleRequest_Rule()
}

type SetRoutingRuleRequest_TrafficBased struct {
	TrafficBased *TrafficBased `protobuf:"bytes,3,opt,name=traffic_based,json=trafficBased,proto3,oneof"`
}

type SetRoutingRuleRequest_PaymodeBased struct {
	PaymodeBased *PayModeBased `protobuf:"bytes,4,opt,name=paymode_based,json=paymodeBased,proto3,oneof"`
}

func (*SetRoutingRuleRequest_TrafficBased) isSetRoutingRuleRequest_Rule() {}

func (*SetRoutingRuleRequest_PaymodeBased) isSetRoutingRuleRequest_Rule() {}

type SetRoutingRuleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *status.Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SetRoutingRuleResponse) Reset() {
	*x = SetRoutingRuleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_router_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRoutingRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRoutingRuleResponse) ProtoMessage() {}

func (x *SetRoutingRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_router_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRoutingRuleResponse.ProtoReflect.Descriptor instead.
func (*SetRoutingRuleResponse) Descriptor() ([]byte, []int) {
	return file_router_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetRoutingRuleResponse) GetStatus() *status.Status {
	if x != nil {
		return x.Status
	}
	return nil
}

var File_router_service_proto protoreflect.FileDescriptor

var file_router_service_proto_rawDesc = []byte{
	0x0a, 0x14, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x17,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x11, 0x70, 0x61, 0x79, 0x2f, 0x70, 0x61, 0x79,
	0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2f, 0x72, 0x75, 0x6c, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x85, 0x01, 0x0a, 0x0c, 0x52, 0x6f, 0x75, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x61,
	0x79, 0x4d, 0x6f, 0x64, 0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x3b, 0x0a, 0x0d, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x2a, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe4, 0x01, 0x0a,
	0x15, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x31,
	0x0a, 0x09, 0x72, 0x75, 0x6c, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x69,
	0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x73, 0x52, 0x08, 0x72, 0x75, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x3b, 0x0a, 0x0d, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x5f, 0x62, 0x61, 0x73,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x54, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x42, 0x61, 0x73, 0x65, 0x64, 0x48, 0x00,
	0x52, 0x0c, 0x74, 0x72, 0x61, 0x66, 0x66, 0x69, 0x63, 0x42, 0x61, 0x73, 0x65, 0x64, 0x12, 0x3b,
	0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x50,
	0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0c, 0x70,
	0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x42, 0x61, 0x73, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04, 0x72,
	0x75, 0x6c, 0x65, 0x22, 0x44, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e,
	0x67, 0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2a, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x32, 0x8f, 0x01, 0x0a, 0x06, 0x52, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x05, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x12, 0x14, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4f, 0x0a, 0x0e, 0x53, 0x65,
	0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x75, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67,
	0x52, 0x75, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x75, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1b, 0x5a, 0x19, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_router_service_proto_rawDescOnce sync.Once
	file_router_service_proto_rawDescData = file_router_service_proto_rawDesc
)

func file_router_service_proto_rawDescGZIP() []byte {
	file_router_service_proto_rawDescOnce.Do(func() {
		file_router_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_router_service_proto_rawDescData)
	})
	return file_router_service_proto_rawDescData
}

var file_router_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_router_service_proto_goTypes = []interface{}{
	(*RouteRequest)(nil),           // 0: router.RouteRequest
	(*RouteResponse)(nil),          // 1: router.RouteResponse
	(*SetRoutingRuleRequest)(nil),  // 2: router.SetRoutingRuleRequest
	(*SetRoutingRuleResponse)(nil), // 3: router.SetRoutingRuleResponse
	(*money.Money)(nil),            // 4: google.type.Money
	(*pay.PayMode)(nil),            // 5: paymode.PayMode
	(*status.Status)(nil),          // 6: google.rpc.Status
	(RoutingRules)(0),              // 7: router.RoutingRules
	(*TrafficBased)(nil),           // 8: router.TrafficBased
	(*PayModeBased)(nil),           // 9: router.PayModeBased
}
var file_router_service_proto_depIdxs = []int32{
	4, // 0: router.RouteRequest.money:type_name -> google.type.Money
	5, // 1: router.RouteRequest.paymode:type_name -> paymode.PayMode
	6, // 2: router.RouteResponse.status:type_name -> google.rpc.Status
	7, // 3: router.SetRoutingRuleRequest.rule_type:type_name -> router.RoutingRules
	8, // 4: router.SetRoutingRuleRequest.traffic_based:type_name -> router.TrafficBased
	9, // 5: router.SetRoutingRuleRequest.paymode_based:type_name -> router.PayModeBased
	6, // 6: router.SetRoutingRuleResponse.status:type_name -> google.rpc.Status
	0, // 7: router.Router.Route:input_type -> router.RouteRequest
	2, // 8: router.Router.SetRoutingRule:input_type -> router.SetRoutingRuleRequest
	1, // 9: router.Router.Route:output_type -> router.RouteResponse
	3, // 10: router.Router.SetRoutingRule:output_type -> router.SetRoutingRuleResponse
	9, // [9:11] is the sub-list for method output_type
	7, // [7:9] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_router_service_proto_init() }
func file_router_service_proto_init() {
	if File_router_service_proto != nil {
		return
	}
	file_router_rules_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_router_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_router_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_router_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRoutingRuleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_router_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRoutingRuleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_router_service_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*SetRoutingRuleRequest_TrafficBased)(nil),
		(*SetRoutingRuleRequest_PaymodeBased)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_router_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_router_service_proto_goTypes,
		DependencyIndexes: file_router_service_proto_depIdxs,
		MessageInfos:      file_router_service_proto_msgTypes,
	}.Build()
	File_router_service_proto = out.File
	file_router_service_proto_rawDesc = nil
	file_router_service_proto_goTypes = nil
	file_router_service_proto_depIdxs = nil
}
