// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: pay/payment.proto

package pay

import (
	money "google.golang.org/genproto/googleapis/type/money"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bank_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Money *money.Money `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
}

func (x *Bank_Transaction) Reset() {
	*x = Bank_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_payment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bank_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bank_Transaction) ProtoMessage() {}

func (x *Bank_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pay_payment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bank_Transaction.ProtoReflect.Descriptor instead.
func (*Bank_Transaction) Descriptor() ([]byte, []int) {
	return file_pay_payment_proto_rawDescGZIP(), []int{0}
}

func (x *Bank_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bank_Transaction) GetMoney() *money.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

type PG_Transaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Money   *money.Money `protobuf:"bytes,2,opt,name=money,proto3" json:"money,omitempty"`
	Paymode *PayMode     `protobuf:"bytes,3,opt,name=paymode,proto3" json:"paymode,omitempty"`
}

func (x *PG_Transaction) Reset() {
	*x = PG_Transaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_payment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PG_Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PG_Transaction) ProtoMessage() {}

func (x *PG_Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_pay_payment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PG_Transaction.ProtoReflect.Descriptor instead.
func (*PG_Transaction) Descriptor() ([]byte, []int) {
	return file_pay_payment_proto_rawDescGZIP(), []int{1}
}

func (x *PG_Transaction) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PG_Transaction) GetMoney() *money.Money {
	if x != nil {
		return x.Money
	}
	return nil
}

func (x *PG_Transaction) GetPaymode() *PayMode {
	if x != nil {
		return x.Paymode
	}
	return nil
}

var File_pay_payment_proto protoreflect.FileDescriptor

var file_pay_payment_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x79, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x61, 0x79, 0x1a, 0x17, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x2f, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x11, 0x70, 0x61, 0x79, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x10, 0x42, 0x61, 0x6e, 0x6b, 0x5f, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x05, 0x6d, 0x6f, 0x6e,
	0x65, 0x79, 0x22, 0x76, 0x0a, 0x0e, 0x50, 0x47, 0x5f, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x79, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x65, 0x79, 0x12, 0x2a,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64,
	0x65, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x6f, 0x64, 0x65, 0x42, 0x18, 0x5a, 0x16, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x70, 0x61, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_payment_proto_rawDescOnce sync.Once
	file_pay_payment_proto_rawDescData = file_pay_payment_proto_rawDesc
)

func file_pay_payment_proto_rawDescGZIP() []byte {
	file_pay_payment_proto_rawDescOnce.Do(func() {
		file_pay_payment_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_payment_proto_rawDescData)
	})
	return file_pay_payment_proto_rawDescData
}

var file_pay_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pay_payment_proto_goTypes = []interface{}{
	(*Bank_Transaction)(nil), // 0: pay.Bank_Transaction
	(*PG_Transaction)(nil),   // 1: pay.PG_Transaction
	(*money.Money)(nil),      // 2: google.type.Money
	(*PayMode)(nil),          // 3: paymode.PayMode
}
var file_pay_payment_proto_depIdxs = []int32{
	2, // 0: pay.Bank_Transaction.money:type_name -> google.type.Money
	2, // 1: pay.PG_Transaction.money:type_name -> google.type.Money
	3, // 2: pay.PG_Transaction.paymode:type_name -> paymode.PayMode
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pay_payment_proto_init() }
func file_pay_payment_proto_init() {
	if File_pay_payment_proto != nil {
		return
	}
	file_pay_paymode_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pay_payment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bank_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_payment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PG_Transaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_payment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pay_payment_proto_goTypes,
		DependencyIndexes: file_pay_payment_proto_depIdxs,
		MessageInfos:      file_pay_payment_proto_msgTypes,
	}.Build()
	File_pay_payment_proto = out.File
	file_pay_payment_proto_rawDesc = nil
	file_pay_payment_proto_goTypes = nil
	file_pay_payment_proto_depIdxs = nil
}
