// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: commons/id_categories.proto

package commons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdCategory int32

const (
	IdCategory_IdCategory_UNDEFINED IdCategory = 0
	IdCategory_TRANSACTION          IdCategory = 1
	IdCategory_CLIENT               IdCategory = 2
)

// Enum value maps for IdCategory.
var (
	IdCategory_name = map[int32]string{
		0: "IdCategory_UNDEFINED",
		1: "TRANSACTION",
		2: "CLIENT",
	}
	IdCategory_value = map[string]int32{
		"IdCategory_UNDEFINED": 0,
		"TRANSACTION":          1,
		"CLIENT":               2,
	}
)

func (x IdCategory) Enum() *IdCategory {
	p := new(IdCategory)
	*p = x
	return p
}

func (x IdCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_id_categories_proto_enumTypes[0].Descriptor()
}

func (IdCategory) Type() protoreflect.EnumType {
	return &file_commons_id_categories_proto_enumTypes[0]
}

func (x IdCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdCategory.Descriptor instead.
func (IdCategory) EnumDescriptor() ([]byte, []int) {
	return file_commons_id_categories_proto_rawDescGZIP(), []int{0}
}

var File_commons_id_categories_proto protoreflect.FileDescriptor

var file_commons_id_categories_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x69, 0x64, 0x5f, 0x63, 0x61, 0x74,
	0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2a, 0x43, 0x0a, 0x0a, 0x49, 0x64, 0x43, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x14, 0x49, 0x64, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f,
	0x72, 0x79, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0f,
	0x0a, 0x0b, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x01, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x02, 0x42, 0x1c, 0x5a, 0x1a, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_commons_id_categories_proto_rawDescOnce sync.Once
	file_commons_id_categories_proto_rawDescData = file_commons_id_categories_proto_rawDesc
)

func file_commons_id_categories_proto_rawDescGZIP() []byte {
	file_commons_id_categories_proto_rawDescOnce.Do(func() {
		file_commons_id_categories_proto_rawDescData = protoimpl.X.CompressGZIP(file_commons_id_categories_proto_rawDescData)
	})
	return file_commons_id_categories_proto_rawDescData
}

var file_commons_id_categories_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commons_id_categories_proto_goTypes = []interface{}{
	(IdCategory)(0), // 0: commons.IdCategory
}
var file_commons_id_categories_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commons_id_categories_proto_init() }
func file_commons_id_categories_proto_init() {
	if File_commons_id_categories_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commons_id_categories_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_id_categories_proto_goTypes,
		DependencyIndexes: file_commons_id_categories_proto_depIdxs,
		EnumInfos:         file_commons_id_categories_proto_enumTypes,
	}.Build()
	File_commons_id_categories_proto = out.File
	file_commons_id_categories_proto_rawDesc = nil
	file_commons_id_categories_proto_goTypes = nil
	file_commons_id_categories_proto_depIdxs = nil
}
