// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.20.3
// source: commons/status.proto

package commons

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status_Type int32

const (
	Status_STATUS_UNDEFINED      Status_Type = 0
	Status_OK                    Status_Type = 1
	Status_INVALID_REQUEST       Status_Type = 2
	Status_UNAUTHORISED          Status_Type = 3
	Status_INTERNAL_SERVER_ERROR Status_Type = 4
	Status_NOT_FOUND             Status_Type = 5
)

// Enum value maps for Status_Type.
var (
	Status_Type_name = map[int32]string{
		0: "STATUS_UNDEFINED",
		1: "OK",
		2: "INVALID_REQUEST",
		3: "UNAUTHORISED",
		4: "INTERNAL_SERVER_ERROR",
		5: "NOT_FOUND",
	}
	Status_Type_value = map[string]int32{
		"STATUS_UNDEFINED":      0,
		"OK":                    1,
		"INVALID_REQUEST":       2,
		"UNAUTHORISED":          3,
		"INTERNAL_SERVER_ERROR": 4,
		"NOT_FOUND":             5,
	}
)

func (x Status_Type) Enum() *Status_Type {
	p := new(Status_Type)
	*p = x
	return p
}

func (x Status_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_commons_status_proto_enumTypes[0].Descriptor()
}

func (Status_Type) Type() protoreflect.EnumType {
	return &file_commons_status_proto_enumTypes[0]
}

func (x Status_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status_Type.Descriptor instead.
func (Status_Type) EnumDescriptor() ([]byte, []int) {
	return file_commons_status_proto_rawDescGZIP(), []int{0, 0}
}

type Status struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type Status_Type `protobuf:"varint,1,opt,name=type,proto3,enum=commons.Status_Type" json:"type,omitempty"`
}

func (x *Status) Reset() {
	*x = Status{}
	if protoimpl.UnsafeEnabled {
		mi := &file_commons_status_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_commons_status_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_commons_status_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetType() Status_Type {
	if x != nil {
		return x.Type
	}
	return Status_STATUS_UNDEFINED
}

var File_commons_status_proto protoreflect.FileDescriptor

var file_commons_status_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x2f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x22,
	0xa9, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x75, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x02, 0x12,
	0x10, 0x0a, 0x0c, 0x55, 0x4e, 0x41, 0x55, 0x54, 0x48, 0x4f, 0x52, 0x49, 0x53, 0x45, 0x44, 0x10,
	0x03, 0x12, 0x19, 0x0a, 0x15, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x45, 0x52, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09,
	0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55, 0x4e, 0x44, 0x10, 0x05, 0x42, 0x1c, 0x5a, 0x1a, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_commons_status_proto_rawDescOnce sync.Once
	file_commons_status_proto_rawDescData = file_commons_status_proto_rawDesc
)

func file_commons_status_proto_rawDescGZIP() []byte {
	file_commons_status_proto_rawDescOnce.Do(func() {
		file_commons_status_proto_rawDescData = protoimpl.X.CompressGZIP(file_commons_status_proto_rawDescData)
	})
	return file_commons_status_proto_rawDescData
}

var file_commons_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commons_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commons_status_proto_goTypes = []interface{}{
	(Status_Type)(0), // 0: commons.Status.Type
	(*Status)(nil),   // 1: commons.Status
}
var file_commons_status_proto_depIdxs = []int32{
	0, // 0: commons.Status.type:type_name -> commons.Status.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commons_status_proto_init() }
func file_commons_status_proto_init() {
	if File_commons_status_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_commons_status_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Status); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_commons_status_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commons_status_proto_goTypes,
		DependencyIndexes: file_commons_status_proto_depIdxs,
		EnumInfos:         file_commons_status_proto_enumTypes,
		MessageInfos:      file_commons_status_proto_msgTypes,
	}.Build()
	File_commons_status_proto = out.File
	file_commons_status_proto_rawDesc = nil
	file_commons_status_proto_goTypes = nil
	file_commons_status_proto_depIdxs = nil
}
